### ISSUE TITLE
Thank you for porting this so that waf is not needed and a portable version!

### ISSUE THREAD

**Issue by 38github** [Sound-Linux-More/lossywav-for-posix#2]
Thank you!

**Comment by zvezdochiot** [comment]
Hi @38github .

What is the `waf` version? I'll take a look. Maybe I'll add a link. Although hardly.

**Comment by 38github** [comment]
@zvezdochiot It is the version of LossyWAV found [here](https://github.com/MoSal/lossywav-for-posix) that I used several years ago but had issues compiling this time around

**Comment by zvezdochiot** [comment]
Hi @38github .

Ok. Good.
