### ISSUE TITLE
LDFLAGS environment variable not preserved

### ISSUE THREAD

**Issue by xiota** [Sound-Linux-More/lossywav-for-posix#3]
Setting `LDFLAGS` is ignored.  The problem is in `Makefile`:
```
LDFLAGS = -s
```

Please change to:
```
LDFLAGS += -s
```

**Comment by zvezdochiot** [comment]
@xiota say:
>Please change to

What for? You can do "it" yourself.

**Comment by xiota** [comment]
The purpose of environment variables is so the user can control build parameters without manually editing the build scripts.  Changing `=` to`+=` preserves the environment variable.

When you say 'do "it" yourself', are you requesting a merge request?  Or are you refusing to make any changes to this repository whatsoever?

**Comment by zvezdochiot** [comment]
@xiota say:
> Or are you refusing to make any changes to this repository whatsoever?

Yes. What for? Everything works. "Keep is simple, stupid".
